version: "3"
services: 
    client:
        build: 
            context: ./
            dockerfile: Dockerfile_client
        hostname: client
        ports: 
            - "8000:8000"
        
    server:
        build: 
            context: ./
            dockerfile: Dockerfile_server
        hostname: server
        ports: 
            - "8001:8001"  

            