FROM ubuntu:latest 

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    git python3

WORKDIR /application
COPY app_client.py .
COPY text.txt .

ENTRYPOINT [ "python3", "app_client.py" ]

